### ISSUE TITLE
Error-Log indicates a deprecation warning regards the MessageEmbed#addField option

### ISSUE THREAD

**Issue by Itz-Toothless** [ScootKit/CustomDCBot#100]
A few Minutes ago, I've discovered this Error while curiously looking into the Error-Logs:

![image](https://user-images.githubusercontent.com/80362356/213030715-186d6a42-7aad-479b-ad87-889d98f5f4c1.png)

The Problem now being the fact that I cannot change the code itself to get this Error fixed.

Could you guys take a look into this please? I would highly appreciate it!

Best Regards,

Itz_Toothless

**Comment by SCDerox** [comment]
Thanks so much for reaching out. This is a warning and no error - you can safely ignore it. We'll gradually fix the lines causing this warning, but functionality should not be affected.
