### ISSUE TITLE
Ladeproblem Dashboard

### ISSUE THREAD

**Issue by LinkLuigiMaster** [ScootKit/CustomDCBot#131]
Moin, hab hier ein Problem gefunden, was ein potenzieller Fehler eventuell sein könnte. 
Ich hab den jetzt nicht überprüft und auch nicht weiter nachgeforscht auf Grund von Zeitmangel bei mir. 

Kurz was ist passiert: 
Ich hab die Module durchsucht bei einem Server, wo ich noch nie vorher Module eingeschalten hatte. 
Nachdem ich meine entsprechende Auswahl getroffen hatte, hab ich gespeichert und reloadet und dann passierte gar nichts mehr. Die Werbung unten Links war ein Placeholder, wo halt Werbung sein sollte und das, was ihr noch auf den Bild hier seht.

![Issue #01 Ladefehler](https://github.com/ScootKit/CustomDCBot/assets/58277126/21b99c91-a9e6-4cd0-94f4-936fbfdefc91)

In der Konsole war ein Fehler, wie auf dem Bild zu sehen. 
Nach einer Minute ungefähr ist die Werbung wieder geladen. 
Nach etwas länger Zeit, hat es dann fertig gespeichert.

**Comment by SCDerox** [comment]
If you have questions or issues with SCNX, please visit [scnx.app/help](https://scnx.app/help). This is the repository for another project.
