### ISSUE TITLE
Translation in French

### ISSUE THREAD

**Issue by WolfyzDev** [ScootKit/CustomDCBot#139]
Hello to you ! I am French (and therefore native French speaker) and a SCNX user!
I noticed that your bot is available in English and German.

This is why I offer to help you translate your bot (and other services) into French, for users in France.
I could provide you with the translation via GitHub (e.g. by making a PR or linking the .json file or sending it to you on Discord).

For example, I could:
- Translate the `en.json` file
- Translate modules one by one via the .json file
- Give you the translations you need for the rest (eg Dashboard or other).

Please note that I am not asking for any specific remuneration, and that I will only translate sentences from English to French (without coding the bot).

Example of how to organize so that I provide you with the translation : 
- I could make a new file with all the French sentences (`locates/fr.json`)
- I could create a new line in the modules .json file, for example:
```json
"description": {
    "en": "Simple tools for admins - move channels and roles via commands or copy an emoji from another server to your server.",
    "de": "Einfache Tools für Admins, um Channel und Rollen per Command zu verschieben und Emojis zu leihen."
    "fr": "De simples outils pour les administrateurs : déplacez les salons  et les rôles via des commandes ou copiez un emoji d'un autre serveur vers votre serveur"
  }
```
- Or any other way to organize that you offer me

I remain listening and waiting for a response from you,
Wolfyz

**Comment by Luispupuis** [comment]
You can ask Chatgbt for all files.
Fork the repo.
Edit the files.
Create a pull request

**Comment by SCDerox** [comment]
This has been discussed off-platform on Discord. If you have experience in translating software products, please contact us on Discord, and we can provide you with access to our Weblate translation system. Please do not use ChatGPT and other translation tools for translating ScootKit products or services.
