### ISSUE TITLE
How to access the Dashboard from a self-hosted bot

### ISSUE THREAD

**Issue by AnderRedna** [ScootKit/CustomDCBot#148]
I cloned the repository and did the local installation, added my bot to my server, but I can't find which port the dashboard is running on. Localhost:????

Thank you very much for the amazing project!

**Comment by hfgd123** [comment]
You don't. The open-source version doesn't come with a dashboard.

**Comment by jateute** [comment]
Hey, the selfhosted version of the bot doesn't have a Dashboard. You can do the configuring with the config files or if you aren't comfortable doing that or don't know how json works you can use the hosted version ([https://scnx.xyz](https://scnx.xyz))

**Comment by jateute** [comment]
And if you got any questions please use [discussions-tab](https://github.com/ScootKit/CustomDCBot/discussions) as stated in the README file
