### ISSUE TITLE
Missing dependency @scderox/ikea-name-generator

### ISSUE THREAD

**Issue by torbenprobst** [ScootKit/CustomDCBot#74]
After installing the packages and starting the bot, following "missing module error" appears:
![image](https://user-images.githubusercontent.com/46575728/189147765-4d88383f-2a5e-41ce-a7d6-e678627e299e.png)

The Module "@scderox/ikea-name-generator" is being used in module/fun/commands/random.js

**Comment by SCDerox** [comment]
Should be fiexed in [c6d70de](https://github.com/ScootKit/CustomDCBot/commit/c6d70deb38ff774f33fbd9454534c5537888d7b2)
