### ISSUE TITLE
Setup klappt nicht

### ISSUE THREAD

**Issue by CreamGamer** [ScootKit/CustomDCBot#82]
npm ci und npm run generate-config klappen nicht
![Screenshot_20221016-190627_Admin Hands](https://user-images.githubusercontent.com/84274591/196048591-46125977-3c68-4e31-a791-e10fe8ad61f9.jpg)
 
![Screenshot_20221016-190635_Admin Hands](https://user-images.githubusercontent.com/84274591/196048601-c1a54f23-3007-4af9-aedf-8f9faa170314.jpg)
![Screenshot_20221016-190640_Admin Hands](https://user-images.githubusercontent.com/84274591/196048603-a3ac77a2-72b1-4f62-b455-2bf1ed148de8.jpg)

npm run generate-config
![Screenshot_20221016-190837_Admin Hands](https://user-images.githubusercontent.com/84274591/196048636-d3995007-47d5-4047-a0dc-b2292095d605.jpg)

**Comment by SCDerox** [comment]
Sorry, but the official language of this repository is English. Please keep your discussions in English. This is not an issue with Custom-Bot. Please follow the installation guide for node-gyp [here](https://github.com/nodejs/node-gyp). If you need ore help with installation, please use the [discussions-tab](https://github.com/ScootKit/CustomDCBot/discussions) of this repository.
