### ISSUE TITLE
Need Help with this Erro CustomDCBot

### ISSUE THREAD

**Issue by amorking1996** [ScootKit/CustomDCBot#89]
hello i need help from this error

i have debian 11
nodejs 16
npm 8

npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated @discordjs/collection@0.7.0: no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
npm WARN deprecated @discordjs/builders@0.16.0: no longer supported
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by uglify-js as of v3.13.0
npm WARN deprecated nlp_compromise@4.12.1: nlp_compromise has been renamed to 'compromise', please update
npm ERR! code 1
npm ERR! path /home/Bot/CustomDCBot/node_modules/erlpack
npm ERR! command failed
npm ERR! command sh -c -- node-gyp rebuild
npm ERR! make: Entering directory '/home/Bot/CustomDCBot/node_modules/erlpack/build'
npm ERR! CC(target) Release/obj.target/zlib/vendor/zlib/adler32.o
npm ERR! make: Leaving directory '/home/Bot/CustomDCBot/node_modules/erlpack/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.18.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args '/home/Bot/CustomDCBot/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'make',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/home/Bot/CustomDCBot/node_modules/erlpack/build/config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/home/Bot/CustomDCBot/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/root/.cache/node-gyp/16.18.1/include/node/common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/16.18.1',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=/home/Bot/CustomDCBot/node_modules/node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/16.18.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=/home/Bot/CustomDCBot/node_modules/erlpack',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: cc: No such file or directory
npm ERR! make: *** [vendor/zlib.target.mk:125: Release/obj.target/zlib/vendor/zlib/adler32.o] Error 127
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: make failed with exit code: 2
npm ERR! gyp ERR! stack at ChildProcess.onExit (/home/Bot/CustomDCBot/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Linux 5.10.0-19-amd64
npm ERR! gyp ERR! command "/usr/bin/node" "/home/Bot/CustomDCBot/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/Bot/CustomDCBot/node_modules/erlpack
npm ERR! gyp ERR! node -v v16.18.1
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:

**Comment by amorking1996** [comment]
5 info lifecycle customdcbot@3.7.0~prestart: customdcbot@3.7.0
6 info lifecycle customdcbot@3.7.0~start: customdcbot@3.7.0
7 verbose lifecycle customdcbot@3.7.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle customdcbot@3.7.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/bot/CustomDCBot/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi>
9 verbose lifecycle customdcbot@3.7.0~start: CWD: /home/bot/CustomDCBot
10 silly lifecycle customdcbot@3.7.0~start: Args: [ '-c', 'node main.js' ]
11 silly lifecycle customdcbot@3.7.0~start: Returned: code: 1  signal: null
12 info lifecycle customdcbot@3.7.0~start: Failed to exec start script
13 verbose stack Error: customdcbot@3.7.0 start: `node main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid customdcbot@3.7.0
15 verbose cwd /home/bot/CustomDCBot/config
16 verbose Linux 5.10.0-19-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.22.12
19 verbose npm  v6.14.16
20 error code ELIFECYCLE
21 error errno 1
22 error customdcbot@3.7.0 start: `node main.js`
22 error Exit status 1
23 error Failed at the customdcbot@3.7.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by SCDerox** [comment]
This is an issue with installing dependencies. Please make sure you meet all dependency requirements. If you need additional help, please use [discussions](https://github.com/ScootKit/CustomDCBot/discussions)

**Comment by amorking1996** [comment]
where can i find the prerequisites

**Comment by amorking1996** [comment]
dependency
